apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: vue-weather-app
  name: vue-weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: vue-weather-app
  template:
    metadata:
      labels:
        run: vue-weather-app
    spec:
      containers:
      - image: gcr.io/cicd-project-334600/vue-weather-app:latest #Replace [PROJECT-ID] accordingly
        name: vue-weather-app
        ports:
        - containerPort: 8080
